### ISSUE TITLE
see state of dealer's hand

### ISSUE THREAD

**Issue by mikekellyio** [rubyloco/script-wars-blackjack#2]
Maybe I'm missing it, but looking through things I don't see a way to see the current state of the dealer's hand. Is that a planned addition?

**Comment by kkirsche** [comment]
My guess is that can be grabbed from the `attr_reader :hand` Which is in lib/script-wars-blackjack/dealer.rb

**Comment by mikekellyio** [comment]
the app has access to that, but the player AI doesn't... the player AI has an `attr_reader :hand` which seems to refer to the player's hand. The player AI currently has no reference to get to the dealer, and thus by extension the `dealer.hand`

**Comment by hmadison** [comment]
Fixed! Thanks!

**Comment by kkirsche** [comment]
Shows what I know from quick peruses and not actually reading lol. Good find :+1:

**Comment by mikekellyio** [comment]
thanks @hmadison for the quick fix!
